import {
  BarChart3,
  CalendarCheck,
  ClipboardCheck,
  CreditCard,
  LayoutDashboard,
  Megaphone,
  MessageSquareText,
  Package,
  Percent,
  Settings,
  Store,
  UserCheck,
  Users,
} from 'lucide-react';

export const menu = [
  { path: '/', label: 'ภาพรวม', icon: LayoutDashboard, menuKey: 'dashboard', roles: ['supervisor', 'admin', 'accounting'] },
  {
    label: 'จัดการตลาด',
    icon: Store,
    menuKey: 'markets',
    children: [
      { path: '/markets', label: 'รายชื่อตลาด' },
      { path: '/market-info', label: 'ข้อมูลทั่วไป' },
      { path: '/booth-types', label: 'แผนผัง' },
      { path: '/booths', label: 'จัดการบูธ' },
      { path: '/visual-plan', label: 'แผนผังเสมือนจริง' },
      { path: '/holiday-calendar', label: 'ปฏิทินวันหยุด' },
      { path: '/market-images', label: 'จัดการรูปภาพตลาด' },
      { path: '/accessories', label: 'จัดการบริการเสริม' },
    ],
  },
  {
    label: 'สินค้า',
    icon: Package,
    menuKey: 'products',
    children: [
      { path: '/product-categories', label: 'ประเภทสินค้า' },
      { path: '/product-groups', label: 'หมวดหมู่สินค้า' },
      { path: '/products', label: 'รายการสินค้า' },
    ],
  },
  {
    label: 'โค้ดส่วนลด',
    icon: Percent,
    menuKey: 'coupons',
    children: [
      { path: '/coupons', label: 'สร้างโค้ดส่วนลด' },
      { path: '/coupon-assignments', label: 'รายการที่แจกโค้ด' },
    ],
  },
  {
    label: 'การจอง',
    icon: CalendarCheck,
    menuKey: 'bookings',
    children: [
      { path: '/bookings', label: 'จองแทนสมาชิก' },
      { path: '/booking-edit', label: 'แก้ไขการจอง' },
      { path: '/booking-edits', label: 'รายการแก้ไขการจอง' },
      { path: '/booking-payment-proofs', label: 'ตรวจสลิปโอนเงิน' },
    ],
  },
  {
    label: 'Report',
    icon: BarChart3,
    menuKey: 'reports',
    children: [
      { path: '/reports', label: 'รายงานการจอง' },
      { path: '/report-booths', label: 'รายงานบูธว่าง' },
      { path: '/report-payments', label: 'รายงานการชำระเงิน' },
      { path: '/report-daily', label: 'รายงานการขายรายวัน' },
      { path: '/report-person', label: 'การจองรายบุคคล' },
    ],
  },
  {
    label: 'ตรวจสอบตลาด',
    icon: ClipboardCheck,
    menuKey: 'market_audit',
    children: [
      { path: '/audit', label: 'ข้อมูลการตรวจสอบ' },
      { path: '/audit-fines', label: 'รายงานค่าปรับค้างจ่าย' },
      { path: '/audit-fines-paid', label: 'รายชื่อผู้จ่ายค่าปรับแบบโอน' },
      { path: '/audit-defective', label: 'รายการสินค้าชำรุด' },
    ],
  },
  {
    label: 'ประกาศ/ประชาสัมพันธ์',
    icon: Megaphone,
    menuKey: 'announcements',
    roles: ['supervisor', 'admin'],
    children: [
      { path: '/announcements/news', label: 'ข่าวสาร' },
    ],
  },
  {
    label: 'รายงานผู้เช่า',
    icon: UserCheck,
    menuKey: 'tenants',
    roles: ['supervisor', 'admin'],
    children: [
      { path: '/tenant-types', label: 'ประเภทผู้เช่า' },
      { path: '/tenants', label: 'รายชื่อผู้เช่า' },
      { path: '/tenants/pending', label: 'ผู้เช่ารอการอนุมัติ' },
    ],
  },
  {
    label: 'บัญชี',
    icon: CreditCard,
    menuKey: 'accounting',
    children: [
      { path: '/accounting', label: 'รายงานแสดงข้อมูลทั้งหมด' },
      { path: '/accounting-payments', label: 'รายงานการชำระเงิน' },
      { path: '/accounting-summary', label: 'รายงานสรุปยอดขาย' },
      { path: '/accounting-documents', label: 'ทะเบียนเอกสารบัญชี' },
      { path: '/accounting-tax-sales', label: 'รายงานภาษีขาย' },
      { path: '/accounting-receivables', label: 'ลูกหนี้ค้างชำระ' },
      { path: '/accounting-reconciliation', label: 'กระทบยอดชำระเงิน' },
      { path: '/accounting-refunds', label: 'คืนเงิน/ใบลดหนี้' },
      { path: '/accounting-product-types', label: 'รายงานประเภทสินค้าที่ขาย' },
    ],
  },
  { path: '/organization-settings', label: 'ตั้งค่าองค์กร', icon: Settings, menuKey: 'organization_settings', roles: ['supervisor'] },
  { path: '/pdpa', label: 'จัดการ PDPA', icon: Settings, menuKey: 'pdpa', roles: ['supervisor'] },
  { path: '/admins', label: 'ผู้ดูแลระบบ', icon: Users, menuKey: 'admins' },
  {
    label: 'แจ้งปัญหา/สอบถาม',
    icon: MessageSquareText,
    menuKey: 'support',
    roles: ['supervisor', 'admin', 'accounting'],
    children: [
      { path: '/support/tickets', label: 'แจ้งปัญหา/สอบถาม' },
      { path: '/support/chat', label: 'แชทกับเจ้าหน้าที่' },
    ],
  },
];
